baseURL = "https://noslogan.org/"
languageCode = "en-uk"
title = "newt@noslogan"

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params]
  description = "nothing to see here, move along"
  github = "https://github.com/nic-gibson"
  twitter = "https://twitter.com/nic_gibson"
  background_color_class = "bg-silver"
  body_classes = "avenir bg-near-white"
  featured_image = '/images/lake-wood.jpg'
  cover_dimming_class = "bg-black-20"
